<%@ Page Language="vb" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" 
    CodeFile="DLRequestStatus.aspx.vb" Inherits="DLRequestStatus" title="Bank Statement Request Status"%>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

 <asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">     
                   
           <telerik:RadScriptManager ID="RadScriptManager1" runat="server" >
               <Scripts>
                   <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js">
                   </asp:ScriptReference>
                   <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js">
                   </asp:ScriptReference>
                   <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js">
                   </asp:ScriptReference> 
               </Scripts> 
           </telerik:RadScriptManager> 
              <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
                 <AjaxSettings>
                    <telerik:AjaxSetting AjaxControlID="RadGrid1">
                        <UpdatedControls>
                            <telerik:AjaxUpdatedControl ControlID="RadGrid1"></telerik:AjaxUpdatedControl>
                        </UpdatedControls>
                    </telerik:AjaxSetting>
                 </AjaxSettings>
           </telerik:RadAjaxManager>

          <table class="centered-cell" style="width: 99%">
              <tr>
                <td class="left-cell" style="width:20%">
                    <asp:CheckBox ID="ShowCompleted" runat="server" AutoPostBack="True" Font-Names="Arial" Font-Size="Small" Text="Show Completed" TextAlign="Left" />
                  </td>
                <td class="centered-cell" style="width: 60%;padding: 1px; font-family: Arial, Helvetica, sans-serif; font-size: small; border-top-color: #A0A0A0; border-right-color: #C0C0C0; border-bottom-color: #C0C0C0; border-left-color: #A0A0A0; font-weight: bold; ">
                    Bank Statement Request Status<br />
                </td>
                <td class="right-cell" style="width:20%">
                    <asp:Label ID="RepToShow" runat="server" Visible="False"></asp:Label>
                    &nbsp;<asp:DropDownList ID="RepList" runat="server" AutoPostBack="True" Font-Names="Arial" Font-Size="Small" style="margin-left: 0px">
                    </asp:DropDownList>
                  </td>
             </tr>
             <tr><td colspan="3">&nbsp;</td></tr>
        </table>

        <table class="centered-cell" style="width:99%">
             <tr>
             <td  style="text-align:center;">
                 <telerik:RadGrid ID="RadGrid1" runat="server" AllowPaging="false" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteColumn="false" AutoGenerateEditColumn="false" PageSize="25" OnNeedDataSource="RadGrid1_NeedDataSource" OnItemCommand="RadGrid1_RowCommand">
                     <MasterTableView>
                         <Columns>
                             <telerik:GridBoundColumn datafield="RepName" HeaderText="Rep" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn datafield="dlReqCode" HeaderText="ReqCode" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="LastSentDate" HeaderText="LastSentDate" DataFormatString="{0:g}" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="DLStatusText" HeaderText="Status" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="DLStatusDate" HeaderText="StsDate" DataFormatString="{0:g}" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="DLAccountsRetrieved" HeaderText="Accts" DataFormatString="{0:f0}" itemstyle-horizontalalign="center" HeaderStyle-HorizontalAlign="center" />
                             <telerik:GridBoundColumn DataField="DBA" HeaderText="DBA" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="MerchantName" HeaderText="Merchant" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="LoanNbr" HeaderText="LoanNbr" DataFormatString="{0:f0}" itemstyle-horizontalalign="right" HeaderStyle-HorizontalAlign="right" />
                             <telerik:GridBoundColumn DataField="FullName" HeaderText="FullName" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridBoundColumn DataField="DLBankName" HeaderText="Bank"  itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="left" />
                             <telerik:GridBoundColumn DataField="EMailAddress" HeaderText="Email" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="left" />
                             <telerik:GridBoundColumn DataField="Phone" HeaderText="SMS Phone" itemstyle-horizontalalign="left" HeaderStyle-HorizontalAlign="Left" />
                             <telerik:GridButtonColumn ButtonType="ImageButton" display="false" UniqueName="Resend" ImageUrl="image/dlsend.png" CommandName="Resend" HeaderText="Resend" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" />
                             <telerik:GridButtonColumn ButtonType="ImageButton" display="false"  uniquename="cancel" ImageUrl="image/dlcancel.png" CommandName="Cancel" HeaderText="Cancel" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" />
                             <telerik:GridButtonColumn ButtonType="ImageButton" display="false" uniquename="Analyze" ImageUrl="image/dlanalysis.png" CommandName="Analyze" HeaderText="Analyze" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" />                       
                        </Columns>
                     </MasterTableView>        
                     <ClientSettings>
                         <Scrolling AllowScroll="true" UseStaticHeaders="True" />
                     </ClientSettings>
                 </telerik:RadGrid>
           </td>
           </tr>
          </table>
          
</asp:Content>